package com.ads.pojo;
// Generated 2017-12-10 14:43:50 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TComment generated by hbm2java
 */
@Entity
@Table(name = "t_comment")
public class TComment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int commentId;//评论id
	private TEpisode TEpisode;//被评论的段子
	private TUser TUser;//评论的用户
	private String commentContent;//评论的内容
	private int commentGood;//评论的点赞数
	private Set<?> TUsers = new HashSet<Object>(0);//点赞此评论的用户

	public TComment() {
	}

	public TComment(int commentId, TEpisode TEpisode, TUser TUser, String commentContent, int commentGood) {
		this.commentId = commentId;
		this.TEpisode = TEpisode;
		this.TUser = TUser;
		this.commentContent = commentContent;
		this.commentGood = commentGood;
	}

	public TComment(int commentId, TEpisode TEpisode, TUser TUser, String commentContent, int commentGood, Set<?> TUsers) {
		this.commentId = commentId;
		this.TEpisode = TEpisode;
		this.TUser = TUser;
		this.commentContent = commentContent;
		this.commentGood = commentGood;
		this.TUsers = TUsers;
	}

	@Id

	@Column(name = "comment_id", unique = true, nullable = false)
	public int getCommentId() {
		return this.commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "episode_id", nullable = false)
	public TEpisode getTEpisode() {
		return this.TEpisode;
	}

	public void setTEpisode(TEpisode TEpisode) {
		this.TEpisode = TEpisode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	@Column(name = "comment_content", nullable = false, length = 1000)
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	@Column(name = "comment_good", nullable = false)
	public int getCommentGood() {
		return this.commentGood;
	}

	public void setCommentGood(int commentGood) {
		this.commentGood = commentGood;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TComments")
	public Set<?> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<?> TUsers) {
		this.TUsers = TUsers;
	}

}
