package com.ads.pojo;
// Generated 2017-12-19 12:16:26 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TComment generated by hbm2java
 */
@Entity
@Table(name = "t_comment", catalog = "episode")
public class TComment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer commentId;
	private TEpisode TEpisode;
	private TUser TUser;
	private String commentContent;
	private int commentGood;
	private Set<TUser> TUsers = new HashSet<TUser>(0);

	public TComment() {
	}

	public TComment(TEpisode TEpisode, TUser TUser, String commentContent, int commentGood) {
		this.TEpisode = TEpisode;
		this.TUser = TUser;
		this.commentContent = commentContent;
		this.commentGood = commentGood;
	}

	public TComment(TEpisode TEpisode, TUser TUser, String commentContent, int commentGood, Set<TUser> TUsers) {
		this.TEpisode = TEpisode;
		this.TUser = TUser;
		this.commentContent = commentContent;
		this.commentGood = commentGood;
		this.TUsers = TUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "comment_id", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	/**
	 * 获取评论的段子
	 * @return TEpisode
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "episode_id", nullable = false)
	public TEpisode getTEpisode() {
		return this.TEpisode;
	}

	public void setTEpisode(TEpisode TEpisode) {
		this.TEpisode = TEpisode;
	}

	/**
	 * 获取发表评论的用户
	 * @return TUser
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	@Column(name = "comment_content", nullable = false, length = 1000)
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	@Column(name = "comment_good", nullable = false)
	public int getCommentGood() {
		return this.commentGood;
	}

	public void setCommentGood(int commentGood) {
		this.commentGood = commentGood;
	}

	/**
	 * 获取点赞此评论的用户
	 * @return Set<TUser>
	 */
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TComments")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

}
