package com.ads.pojo;
// Generated 2017-12-18 22:17:33 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TComment generated by hbm2java
 */
@Entity
@Table(name = "t_comment", catalog = "episode")
public class TComment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer commentId;
	private TEpisode TEpisode;//此评论所评论的段子
	private TUser TUser;//此评论的发表者
	private String commentContent;//评论内容
	private int commentGood;//评论点赞数
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TUser> TUsers_1 = new HashSet<TUser>(0);

	public TComment() {
	}

	public TComment(TEpisode TEpisode, TUser TUser, String commentContent, int commentGood) {
		this.TEpisode = TEpisode;
		this.TUser = TUser;
		this.commentContent = commentContent;
		this.commentGood = commentGood;
	}

	public TComment(TEpisode TEpisode, TUser TUser, String commentContent, int commentGood, Set<TUser> TUsers,
			Set<TUser> TUsers_1) {
		this.TEpisode = TEpisode;
		this.TUser = TUser;
		this.commentContent = commentContent;
		this.commentGood = commentGood;
		this.TUsers = TUsers;
		this.TUsers_1 = TUsers_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "comment_id", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	/**
	 * 获取此评论所评论的段子
	 * @return TEpisode
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "episode_id", nullable = false)
	public TEpisode getTEpisode() {
		return this.TEpisode;
	}

	public void setTEpisode(TEpisode TEpisode) {
		this.TEpisode = TEpisode;
	}

	/**
	 * 获取此评论的发表者
	 * @return TUser
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	/**
	 * 获取评论内容
	 * @return String
	 */
	@Column(name = "comment_content", nullable = false, length = 1000)
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	/**
	 * 获取评论点赞数
	 * @return int
	 */
	@Column(name = "comment_good", nullable = false)
	public int getCommentGood() {
		return this.commentGood;
	}

	public void setCommentGood(int commentGood) {
		this.commentGood = commentGood;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TComments")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TComments")
	public Set<TUser> getTUsers_1() {
		return this.TUsers_1;
	}

	public void setTUsers_1(Set<TUser> TUsers_1) {
		this.TUsers_1 = TUsers_1;
	}

}
