package com.ads.pojo;
// Generated 2017-12-19 12:16:26 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEpisode generated by hbm2java
 */
@Entity
@Table(name = "t_episode", catalog = "episode")
public class TEpisode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer episodeId;
	private Date addDate;
	private String episodeContent;
	private int episodeGood;
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TComment> TComments = new HashSet<TComment>(0);
	private Set<TUser> TUsers_1 = new HashSet<TUser>(0);

	public TEpisode() {
	}

	public TEpisode(Date addDate, String episodeContent, int episodeGood) {
		this.addDate = addDate;
		this.episodeContent = episodeContent;
		this.episodeGood = episodeGood;
	}

	public TEpisode(Date addDate, String episodeContent, int episodeGood, Set<TUser> TUsers, Set<TComment> TComments,
			Set<TUser> TUsers_1) {
		this.addDate = addDate;
		this.episodeContent = episodeContent;
		this.episodeGood = episodeGood;
		this.TUsers = TUsers;
		this.TComments = TComments;
		this.TUsers_1 = TUsers_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "episode_id", unique = true, nullable = false)
	public Integer getEpisodeId() {
		return this.episodeId;
	}

	public void setEpisodeId(Integer episodeId) {
		this.episodeId = episodeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "add_date", nullable = false, length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Column(name = "episode_content", nullable = false, length = 1000)
	public String getEpisodeContent() {
		return this.episodeContent;
	}

	public void setEpisodeContent(String episodeContent) {
		this.episodeContent = episodeContent;
	}

	@Column(name = "episode_good", nullable = false)
	public int getEpisodeGood() {
		return this.episodeGood;
	}

	public void setEpisodeGood(int episodeGood) {
		this.episodeGood = episodeGood;
	}

	/**
	 * 获取收藏此段子的用户
	 * @return Set<TUser>
	 */
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TEpisodes")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	/**
	 * 用户此段子下的评论
	 * @return Set<TComment>
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEpisode")
	public Set<TComment> getTComments() {
		return this.TComments;
	}

	public void setTComments(Set<TComment> TComments) {
		this.TComments = TComments;
	}

	/**
	 * 获取点赞此段子的用户
	 * @return Set<TUser>
	 */
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TEpisodes")
	public Set<TUser> getTUsers_1() {
		return this.TUsers_1;
	}

	public void setTUsers_1(Set<TUser> TUsers_1) {
		this.TUsers_1 = TUsers_1;
	}

	@Override
	public String toString() {
		return "TEpisode [episodeId=" + episodeId + ", addDate=" + addDate + ", episodeContent=" + episodeContent
				+ ", episodeGood=" + episodeGood + ", TUsers=" + TUsers + ", TComments=" + TComments + ", TUsers_1="
				+ TUsers_1 + "]";
	}

}
