package com.ads.pojo;
// Generated 2017-12-18 22:17:33 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEpisode generated by hbm2java
 */
@Entity
@Table(name = "t_episode", catalog = "episode")
public class TEpisode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer episodeId;
	private String episodeContent;//段子内容
	private int episodeGood;//段子点赞数
	private Date addDate;//段子添加日期
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TUser> TUsers_1 = new HashSet<TUser>(0);
	private Set<TComment> TComments = new HashSet<TComment>(0);
	private Set<TComment> TComments_1 = new HashSet<TComment>(0);
	private Set<TUser> TUsers_2 = new HashSet<TUser>(0);
	private Set<TUser> TUsers_3 = new HashSet<TUser>(0);

	public TEpisode() {
	}

	public TEpisode(String episodeContent, int episodeGood, Date addDate) {
		this.episodeContent = episodeContent;
		this.episodeGood = episodeGood;
		this.addDate = addDate;
	}

	public TEpisode(String episodeContent, int episodeGood, Date addDate, Set<TUser> TUsers, Set<TUser> TUsers_1,
			Set<TComment> TComments, Set<TComment> TComments_1, Set<TUser> TUsers_2, Set<TUser> TUsers_3) {
		this.episodeContent = episodeContent;
		this.episodeGood = episodeGood;
		this.addDate = addDate;
		this.TUsers = TUsers;
		this.TUsers_1 = TUsers_1;
		this.TComments = TComments;
		this.TComments_1 = TComments_1;
		this.TUsers_2 = TUsers_2;
		this.TUsers_3 = TUsers_3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "episode_id", unique = true, nullable = false)
	public Integer getEpisodeId() {
		return this.episodeId;
	}

	public void setEpisodeId(Integer episodeId) {
		this.episodeId = episodeId;
	}

	@Column(name = "episode_content", nullable = false, length = 1000)
	public String getEpisodeContent() {
		return this.episodeContent;
	}

	public void setEpisodeContent(String episodeContent) {
		this.episodeContent = episodeContent;
	}

	@Column(name = "episode_good", nullable = false)
	public int getEpisodeGood() {
		return this.episodeGood;
	}

	public void setEpisodeGood(int episodeGood) {
		this.episodeGood = episodeGood;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "add_date", nullable = false, length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TEpisodes")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TEpisodes")
	public Set<TUser> getTUsers_1() {
		return this.TUsers_1;
	}

	public void setTUsers_1(Set<TUser> TUsers_1) {
		this.TUsers_1 = TUsers_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEpisode")
	public Set<TComment> getTComments() {
		return this.TComments;
	}

	public void setTComments(Set<TComment> TComments) {
		this.TComments = TComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEpisode")
	public Set<TComment> getTComments_1() {
		return this.TComments_1;
	}

	public void setTComments_1(Set<TComment> TComments_1) {
		this.TComments_1 = TComments_1;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TEpisodes")
	public Set<TUser> getTUsers_2() {
		return this.TUsers_2;
	}

	public void setTUsers_2(Set<TUser> TUsers_2) {
		this.TUsers_2 = TUsers_2;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TEpisodes")
	public Set<TUser> getTUsers_3() {
		return this.TUsers_3;
	}

	public void setTUsers_3(Set<TUser> TUsers_3) {
		this.TUsers_3 = TUsers_3;
	}

}
