package com.ads.pojo;
// Generated 2017-12-10 14:43:50 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEpisode generated by hbm2java
 */
@Entity
@Table(name = "t_episode")
public class TEpisode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int episodeId;
	private String episodeContent;
	private int episodeGood;
	private Date addDate;
	private Set<?> TUsers = new HashSet<Object>(0);
	private Set<?> TComments = new HashSet<Object>(0);
	private Set<?> TUsers_1 = new HashSet<Object>(0);

	public TEpisode() {
	}

	public TEpisode(int episodeId, String episodeContent, int episodeGood, Date addDate) {
		this.episodeId = episodeId;
		this.episodeContent = episodeContent;
		this.episodeGood = episodeGood;
		this.addDate = addDate;
	}

	public TEpisode(int episodeId, String episodeContent, int episodeGood, Date addDate, Set<?> TUsers, Set<?> TComments,
			Set<?> TUsers_1) {
		this.episodeId = episodeId;
		this.episodeContent = episodeContent;
		this.episodeGood = episodeGood;
		this.addDate = addDate;
		this.TUsers = TUsers;
		this.TComments = TComments;
		this.TUsers_1 = TUsers_1;
	}

	@Id

	@Column(name = "episode_id", unique = true, nullable = false)
	public int getEpisodeId() {
		return this.episodeId;
	}

	public void setEpisodeId(int episodeId) {
		this.episodeId = episodeId;
	}

	@Column(name = "episode_content", nullable = false, length = 1000)
	public String getEpisodeContent() {
		return this.episodeContent;
	}

	public void setEpisodeContent(String episodeContent) {
		this.episodeContent = episodeContent;
	}

	@Column(name = "episode_good", nullable = false)
	public int getEpisodeGood() {
		return this.episodeGood;
	}

	public void setEpisodeGood(int episodeGood) {
		this.episodeGood = episodeGood;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "add_date", nullable = false, length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TEpisodes")
	public Set<?> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<?> TUsers) {
		this.TUsers = TUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEpisode")
	public Set<?> getTComments() {
		return this.TComments;
	}

	public void setTComments(Set<?> TComments) {
		this.TComments = TComments;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TEpisodes")
	public Set<?> getTUsers_1() {
		return this.TUsers_1;
	}

	public void setTUsers_1(Set<?> TUsers_1) {
		this.TUsers_1 = TUsers_1;
	}

}
