package com.ads.pojo;
// Generated 2017-12-10 14:43:50 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "t_user")
public class TUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int userId;
	private String userPassword;
	private String userImage;
	private int userGender;
	private String userNickname;
	private Date loginTime;
	private Set<?> TComments = new HashSet<Object>(0);
	private Set<?> TEpisodes = new HashSet<Object>(0);
	private Set<?> TComments_1 = new HashSet<Object>(0);
	private Set<?> TEpisodes_1 = new HashSet<Object>(0);

	public TUser() {
	}

	public TUser(int userId, String userPassword, String userImage, int userGender, String userNickname,
			Date loginTime) {
		this.userId = userId;
		this.userPassword = userPassword;
		this.userImage = userImage;
		this.userGender = userGender;
		this.userNickname = userNickname;
		this.loginTime = loginTime;
	}

	public TUser(int userId, String userPassword, String userImage, int userGender, String userNickname, Date loginTime,
			Set<?> TComments, Set<?> TEpisodes, Set<?> TComments_1, Set<?> TEpisodes_1) {
		this.userId = userId;
		this.userPassword = userPassword;
		this.userImage = userImage;
		this.userGender = userGender;
		this.userNickname = userNickname;
		this.loginTime = loginTime;
		this.TComments = TComments;
		this.TEpisodes = TEpisodes;
		this.TComments_1 = TComments_1;
		this.TEpisodes_1 = TEpisodes_1;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "user_password", nullable = false, length = 20)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_image", nullable = false, length = 100)
	public String getUserImage() {
		return this.userImage;
	}

	public void setUserImage(String userImage) {
		this.userImage = userImage;
	}

	@Column(name = "user_gender", nullable = false)
	public int getUserGender() {
		return this.userGender;
	}

	public void setUserGender(int userGender) {
		this.userGender = userGender;
	}

	@Column(name = "user_nickname", nullable = false, length = 20)
	public String getUserNickname() {
		return this.userNickname;
	}

	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "login_time", nullable = false, length = 10)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_good_comment", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "comment_id", nullable = false, updatable = false) })
	public Set<?> getTComments() {
		return this.TComments;
	}

	public void setTComments(Set<?> TComments) {
		this.TComments = TComments;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_collect", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "episode_id", nullable = false, updatable = false) })
	public Set<?> getTEpisodes() {
		return this.TEpisodes;
	}

	public void setTEpisodes(Set<?> TEpisodes) {
		this.TEpisodes = TEpisodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUser")
	public Set<?> getTComments_1() {
		return this.TComments_1;
	}

	public void setTComments_1(Set<?> TComments_1) {
		this.TComments_1 = TComments_1;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_good_episode", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "episode_id", nullable = false, updatable = false) })
	public Set<?> getTEpisodes_1() {
		return this.TEpisodes_1;
	}

	public void setTEpisodes_1(Set<?> TEpisodes_1) {
		this.TEpisodes_1 = TEpisodes_1;
	}

}
