package com.ads.pojo;
// Generated 2017-12-18 22:17:33 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "t_user", catalog = "episode")
public class TUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int userId;
	private String userPassword;//用户密码
	private String userImage;//用户头像
	private int userGender;//用户性别
	private String userNickname;//用户昵称
	private Date loginTime;//最近登录时间
	private Set<TEpisode> TEpisodes = new HashSet<TEpisode>(0);
	private Set<TComment> TComments = new HashSet<TComment>(0);
	private Set<TComment> TComments_1 = new HashSet<TComment>(0);
	private Set<TEpisode> TEpisodes_1 = new HashSet<TEpisode>(0);
	private Set<TComment> TComments_2 = new HashSet<TComment>(0);
	private Set<TEpisode> TEpisodes_2 = new HashSet<TEpisode>(0);
	private Set<TComment> TComments_3 = new HashSet<TComment>(0);
	private Set<TEpisode> TEpisodes_3 = new HashSet<TEpisode>(0);

	public TUser() {
	}

	public TUser(int userId, String userPassword, String userImage, int userGender, String userNickname,
			Date loginTime) {
		this.userId = userId;
		this.userPassword = userPassword;
		this.userImage = userImage;
		this.userGender = userGender;
		this.userNickname = userNickname;
		this.loginTime = loginTime;
	}

	public TUser(int userId, String userPassword, String userImage, int userGender, String userNickname, Date loginTime,
			Set<TEpisode> TEpisodes, Set<TComment> TComments, Set<TComment> TComments_1, Set<TEpisode> TEpisodes_1,
			Set<TComment> TComments_2, Set<TEpisode> TEpisodes_2, Set<TComment> TComments_3,
			Set<TEpisode> TEpisodes_3) {
		this.userId = userId;
		this.userPassword = userPassword;
		this.userImage = userImage;
		this.userGender = userGender;
		this.userNickname = userNickname;
		this.loginTime = loginTime;
		this.TEpisodes = TEpisodes;
		this.TComments = TComments;
		this.TComments_1 = TComments_1;
		this.TEpisodes_1 = TEpisodes_1;
		this.TComments_2 = TComments_2;
		this.TEpisodes_2 = TEpisodes_2;
		this.TComments_3 = TComments_3;
		this.TEpisodes_3 = TEpisodes_3;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "user_password", nullable = false, length = 20)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_image", nullable = false, length = 100)
	public String getUserImage() {
		return this.userImage;
	}

	public void setUserImage(String userImage) {
		this.userImage = userImage;
	}

	@Column(name = "user_gender", nullable = false)
	public int getUserGender() {
		return this.userGender;
	}

	public void setUserGender(int userGender) {
		this.userGender = userGender;
	}

	@Column(name = "user_nickname", nullable = false, length = 20)
	public String getUserNickname() {
		return this.userNickname;
	}

	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "login_time", nullable = false, length = 10)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	/**
	 * 获取此用户收藏的段子
	 * @return Set<TEpisode>
	 */
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_collect", catalog = "episode", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "episode_id", nullable = false, updatable = false) })
	public Set<TEpisode> getTEpisodes() {
		return this.TEpisodes;
	}

	public void setTEpisodes(Set<TEpisode> TEpisodes) {
		this.TEpisodes = TEpisodes;
	}

	/**
	 * 获取此用户点赞过的评论
	 * @return Set<TComment>
	 */
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_good_comment", catalog = "episode", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "comment_id", nullable = false, updatable = false) })
	public Set<TComment> getTComments() {
		return this.TComments;
	}

	public void setTComments(Set<TComment> TComments) {
		this.TComments = TComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUser")
	public Set<TComment> getTComments_1() {
		return this.TComments_1;
	}

	public void setTComments_1(Set<TComment> TComments_1) {
		this.TComments_1 = TComments_1;
	}

	/**
	 * 获取此用户点赞过的段子
	 * @return Set<TEpisode>
	 */
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_good_episode", catalog = "episode", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "episode_id", nullable = false, updatable = false) })
	public Set<TEpisode> getTEpisodes_1() {
		return this.TEpisodes_1;
	}

	public void setTEpisodes_1(Set<TEpisode> TEpisodes_1) {
		this.TEpisodes_1 = TEpisodes_1;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_good_comment", catalog = "episode", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "comment_id", nullable = false, updatable = false) })
	public Set<TComment> getTComments_2() {
		return this.TComments_2;
	}

	public void setTComments_2(Set<TComment> TComments_2) {
		this.TComments_2 = TComments_2;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_collect", catalog = "episode", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "episode_id", nullable = false, updatable = false) })
	public Set<TEpisode> getTEpisodes_2() {
		return this.TEpisodes_2;
	}

	public void setTEpisodes_2(Set<TEpisode> TEpisodes_2) {
		this.TEpisodes_2 = TEpisodes_2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUser")
	public Set<TComment> getTComments_3() {
		return this.TComments_3;
	}

	public void setTComments_3(Set<TComment> TComments_3) {
		this.TComments_3 = TComments_3;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_good_episode", catalog = "episode", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "episode_id", nullable = false, updatable = false) })
	public Set<TEpisode> getTEpisodes_3() {
		return this.TEpisodes_3;
	}

	public void setTEpisodes_3(Set<TEpisode> TEpisodes_3) {
		this.TEpisodes_3 = TEpisodes_3;
	}

}
